#Síkidomok v0.1
from tkinter import *

foablak = Tk()
foablak.title("Síkidomok")
foablak.geometry("1024x768")
abl_szelesseg = 1024
abl_magassag = 768
kep_szelesseg = foablak.winfo_screenwidth()
kep_magassag = foablak.winfo_screenheight()
center_x = int(kep_szelesseg/2 - abl_szelesseg / 2)
center_y = int(kep_magassag/2 - abl_magassag / 2)
foablak.resizable(False, False)
foablak.iconphoto(True, PhotoImage(file='./kellekek/negyzetikon.png'))
filename = PhotoImage(file = "./kellekek/MPP+LOGO-12.png")
background_label = Label(foablak, image=filename)
background_label.place(x=0, y=0, relwidth=1, relheight=1)
def Kerulet():
        a=eval(mezo1.get())
        b=eval(mezo2.get())
        c=eval(mezo3.get())
        Kerület=4*a
        mezo4.delete(0,END)
        mezo4.insert(0,str(Kerület))           

def Terulet():
    a=eval(mezo1.get())
    b=eval(mezo2.get())
    c=eval(mezo3.get())
    Terület=4*a
    mezo4.delete(0,END)
    mezo4.insert(0,str(Terület))

menusor=Frame(foablak)
menusor.pack(side=TOP, fill=X)
menu1=Menubutton(menusor, text='Négyzet', underline=0)
menu1.pack(side=LEFT)
Szam1=Menu(menu1)
Szam1.add_command(label='Számítás', command=, underline=0)
menu1.config(menu=Szam1)
menu2=Menubutton(menusor, text='Téglalap', underline=0)
menu2.pack(side=LEFT)
Szam2=Menu(menu2)
Szam2.add_command(label='Számítás', command=, underline=0)
menu2.config(menu=Szam2)
menu3=Menubutton(menusor, text='Háromszög', underline=0)
menu3.pack(side=LEFT)
Szam3=Menu(menu3)
Szam3.add_command(label='Számítás', command=, underline=0)
menu3.config(menu=Szam3)
menu4=Menubutton(menusor, text='Trapéz', underline=0)
menu4.pack(side=LEFT)
Szam4=Menu(menu4)
Szam4.add_command(label='Számítás', command=, underline=0)
menu4.config(menu=Szam4)
menu5=Menubutton(menusor, text='Paralelogramma', underline=0)
menu5.pack(side=LEFT)
Szam5=Menu(menu5)
Szam5.add_command(label='Számítás', command=, underline=0)
menu5.config(menu=Szam5)
menu6=Menubutton(menusor, text='Deltoid', underline=0)
menu6.pack(side=LEFT)
Szam6=Menu(menu6)
Szam6.add_command(label='Számítás', command=, underline=0)
menu6.config(menu=Szam6)
menu7=Menubutton(menusor, text='Rombusz', underline=0)
menu7.pack(side=LEFT)
Szam7=Menu(menu7)
Szam7.add_command(label='Számítás', command=, underline=0)
menu7.config(menu=Szam7)
menu8=Menubutton(menusor, text='Kör', underline=0)
menu8.pack(side=LEFT)
Szam8=Menu(menu8)
Szam8.add_command(label='Számítás', command=, underline=0)
menu8.config(menu=Szam8)

foablak.mainloop()