#Síkidomok v0.1
from tkinter import *

foablak = Tk()
foablak.title("Síkidomok")
foablak.geometry("1024x768")
abl_szelesseg = 1024
abl_magassag = 768
kep_szelesseg = foablak.winfo_screenwidth()
kep_magassag = foablak.winfo_screenheight()
center_x = int(kep_szelesseg/2 - abl_szelesseg / 2)
center_y = int(kep_magassag/2 - abl_magassag / 2)
foablak.resizable(False, False)
foablak.iconphoto(True, PhotoImage(file='./kellekek/negyzetikon.png'))
filename = PhotoImage(file = "./kellekek/MPP+LOGO-12.png")
background_label = Label(foablak, image=filename)
background_label.place(x=0, y=0, relwidth=1, relheight=1)
menusor=Frame(foablak)
menusor.pack(side=TOP, fill=X)
menu1=Menubutton(menusor, text='Négyzet', underline=0)
menu1.pack(side=LEFT)
menu2=Menubutton(menusor, text='Téglalap', underline=0)
menu2.pack(side=LEFT)
menu3=Menubutton(menusor, text='Háromszög', underline=0)
menu3.pack(side=LEFT)
menu4=Menubutton(menusor, text='Trapéz', underline=0)
menu4.pack(side=LEFT)
menu5=Menubutton(menusor, text='Paralelogramma', underline=0)
menu5.pack(side=LEFT)
menu6=Menubutton(menusor, text='Deltoid', underline=0)
menu6.pack(side=LEFT)
menu7=Menubutton(menusor, text='Rombusz', underline=0)
menu7.pack(side=LEFT)
menu8=Menubutton(menusor, text='Kör', underline=0)
menu8.pack(side=LEFT)

foablak.mainloop()